### ISSUE TITLE
Missing Twitter Handler for @shinytoyrobots

### ISSUE THREAD

**Issue by baumannzone** [jlengstorf/jason.energy#47]
In the post **site/posts/106-be-kind/be-kind.md**, you mention a Twitter account (@shinytoyrobots) which no longer exists. Unfortunately, I don't know the correct handle. Could you please update it?

You can find the relevant line here: [link to the file](https://github.com/jlengstorf/jason.energy/blob/c383908fbf772439d00b6b91b893f6fb0cacd771/site/posts/106-be-kind/be-kind.md?plain=1#L77).

---
BTW, you're one of my favorite tech influencers. Your work is super inspiring and motivating! 

boop boop!!

**Comment by jlengstorf** [comment]
thanks @baumannzone! I just pushed a change in 0b4dc79 that updates Robin's link to his website. looks like he deleted his Twitter
